services:
  ubuntu:
    container_name: workstation_${COMPOSE_PROJECT_NAME}
    image: mcr.microsoft.com/devcontainers/base:ubuntu-${UBUNTU_VERSION}
    ports:
      - "${HTTP_PORT}:8000"
      - "${VITE_PORT}:5173"
    restart: "unless-stopped"
    tty: true
    stop_signal: SIGTERM
    volumes:
      - ./:/${WORKSPACE_FOLDER}
      - ~/.gitconfig:/root/.gitconfig
      - ~/.git-credentials:/root/.git-credentials
    networks:
      - regal_network

networks:
  regal_network:
    name: regal_network
    driver: bridge